Add base infrastructure for the TeamSevenAgent
btarifi10/SOMAS2023-Team7 pull request #1
Opened 2023-11-19 03:27 UTC by btarifi10

This pull request adds code and functionality for a base implementation of our team's agent.

Couple of things to check out:
* The `BaseTeamSevenBiker` embeds the `BaseBiker`, meaning it essentially "inherits" all the functions.  The goal is to override all the BaseBiker functions where necessary
* I have modelled a couple of the responsibilities as different frameworks which together can compose the different facets of the agent.
   - These are not yet exhaustive and the inputs are currently just a skeleton
   - Modelling the agent like this will mean we can get new behaviours simply by defining a new framework and plugging it into the agent.
* I made the spawner only spawn our agents. This commit can be dropped when we want to merge or test things later

Since these are mainly skeletons and frameworks I didn't yet write any tests, but I ran `go run .` and there were no errors so we ball

**Note: You'll notice this change is being merged to the branch `main-team-7` and not `main`.**

2023-11-19 18:28 UTC, WillPowellUk requested changes
Nice work @btarifi10! I really like the modularized decision framework idea and i hope this will allow the others to populate functions in these frameworks and not having to rely on other decisions made.

I think the main thing that's missing is the big daddy class called EnvironmentHandler.go lets say. This will hold wrapper methods for the outside world, which will change depending on if we need to message to get information or whether it's avaialble to us from the gamestate. For example right now getting an agents colour could look like: 

``` 
func (env *EnvironmentHandler) GetAgentColour(bikeId uuid.UUID, agentId uuid.UUID){
	return env.FindAgent(bikeId, agentId).GetColour()
}

func (env *EnvironmentHandler) FindAgent(bikeId uuid.UUID, agentId uuid.UUID){
	bike = bikeId[env.gameState.GetMegaBikes()]
	agentsOnBike := bike.GetAgents()
		for agent := range(agentsOnBike){
			if agent.uuid == agentid{
				return agent
			}
		}
	return errorNotFound
}

```
Then if say we need agent forces and agent colours to evaluate trust inside SocialNetwork class. We could instantiante and populate like so:

``` 
type SocialConnectionInput {
	agentForces [uuid.UUID]utils.Forces
        agentColours [uuid.UUID]utils.Colour
   }

func (sn *SocialNetwork) UpdateInputs() {
	inputs := SocialConnectionInput{
		agentForces: env.GetAgentForces(),
		agentColours: env.GetAgentColours(),
	}
}
```

2023-11-19 18:28 UTC, WillPowellUk commented on internal/clients/team7/frameworks/BikeDecisionFramework.go
> +	OnBike BikeDecisionType = iota
There is already a type in BaseBiker.go like this, so let's use that one instead
 ```
type BikerAction int

const (
	Pedal BikerAction = iota
	ChangeBike
)
```

2023-11-19 18:28 UTC, WillPowellUk commented on internal/clients/team7/frameworks/BikeDecisionFramework.go
> +type BikeDecision struct {
I would use BikerAction instead (see above)

2023-11-19 18:28 UTC, WillPowellUk commented on internal/clients/team7/frameworks/SocialNetwork.go
> +func updateTrustLevel(currentTrustLevel float64, forces utils.Forces) float64 {
I think this should be a method of the SocialNetwork class and then have access to SocialConnectionInput and other. Since it will need context for determining if another agent's force is helpful or a hinderance, such as:

-  Our agent's force vs this agents force,
-  what it's intention was compared to what it's action was
-  the energey level of the agent
- connectionAge etc.

Additionally, since there will be other agent interactions other than pedalling that will affect trust, we could rename this to updateTrustLevelFromForce.

2023-11-19 18:34 UTC, btarifi10 commented on internal/clients/team7/frameworks/SocialNetwork.go
> +func updateTrustLevel(currentTrustLevel float64, forces utils.Forces) float64 {
Oh yeah agreed 100%. This was definitely intended to be part of the class, must have just written the function like this by mistake.

2023-11-19 18:37 UTC, btarifi10 commented on internal/clients/team7/frameworks/BikeDecisionFramework.go
> +	OnBike BikeDecisionType = iota
I could probably rename this to be a bit clearer. I think that that enum could work for what I've done here but the intention is to have this framework for all the decisions about bikes, so "OnBike" is meant to produce a decision when we are on the bike (which would result in either staying on the bike or getting off) and the "OffBike" is meant for decisions when we are disembodied and need to find another bike

2023-11-19 18:47 UTC, WillPowellUk commented on internal/clients/team7/frameworks/BikeDecisionFramework.go
> +	OnBike BikeDecisionType = iota
Okay sure, just a quick rename to distinguish. I know pro programmers get a bit bored of comments but you can add a few ;)

2023-11-19 23:15 UTC, btarifi10 commented
Thanks for the review @WillPowellUk . I've made the requested changes and added some comments around parameters, definitions and intentions.

2023-11-20 08:50 UTC, WillPowellUk approved these changes

2023-11-20 13:08 UTC, merged